function [K]=KTimoY(Pr)


%     a1=(12*Pr.Ge.kappa*Pr.Ge.A*...
%         Pr.Mt.G.*Pr.Mt.YM*Pr.Ge.I)/...
%         (Pr.Ge.L*(Pr.Ge.A*Pr.Mt.G.*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa-...
%         12*Pr.Ge.I*Pr.Mt.YM));
%     
%     a2=(6.*Pr.Ge.kappa*...
%         Pr.Ge.A*...
%         Pr.Mt.G*...
%         Pr.Mt.YM*...
%         Pr.Ge.I)/...
%         (Pr.Ge.A*Pr.Mt.G*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa-...
%         12*Pr.Ge.I*Pr.Mt.YM);
%     
%     a3=a2;
%     
%     a4=4.*(Pr.Ge.A*Pr.Mt.G*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa-...
%         3*Pr.Ge.I*Pr.Mt.YM)*Pr.Mt.YM*Pr.Ge.I/...
%         Pr.Ge.L*(Pr.Ge.A*Pr.Mt.G*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa-...
%         12*Pr.Ge.I*Pr.Mt.YM);
%     
%     a5=2.*(Pr.Ge.A*Pr.Mt.G*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa+...
%         6*Pr.Ge.I*Pr.Mt.YM)*Pr.Mt.YM*Pr.Ge.I/...
%         Pr.Ge.L*(Pr.Ge.A*Pr.Mt.G*Pr.Ge.L*Pr.Ge.L*Pr.Ge.kappa-...
%         12*Pr.Ge.I*Pr.Mt.YM);
%     
%     
%     K=[a1,a2,-a1,a3;...
%        a2,a4,-a2,a5;...
%        -a1,-a2,a1,-a2;...
%        a3,a5,-a2,a4];

kfix=[1 0 0 0;...
      0 -1 0 0;...
      0 0 1 0;...
      0 0 0 -1];

K=KTimoZ(Pr);
K=(kfix.')*(K*kfix);
end