      SUBROUTINE SDVINI(STATEV,COORDS,NSTATV,NCRDS,NOEL,NPT,
     1 LAYER,KSPT)
C
      INCLUDE 'ABA_PARAM.INC'
C
      INTEGER I
	  DIMENSION STATEV(NSTATV),COORDS(NCRDS)
      
      include 'GNDSPLIT.f'
	  
	  
	  STATEV(26)=GND(NPT,NOEL)

      RETURN
      END